version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-super}
      PGDATA: /data/postgres
    volumes:
      - .local/postgres/data:/data/postgres
      - ./backups:/backups
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - supergroup

  redis:
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - .local/redis/data:/data
    networks:
      - supergroup

  web:
    image: nginx:1.21
    container_name: web
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - .client/dist:/dist
      - .client/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - supergroup

networks:
  supergroup:
    driver: bridge
